CREATE TABLE IF NOT EXISTS posts (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, title VARCHAR(50) NOT NULL) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS users (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(50) NOT NULL, mail VARCHAR(100) NOT NULL UNIQUE) ENGINE=InnoDB;